---
abstract: 'Interface to the Barcelona Metro Map.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0505, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Map-Tube-Barcelona
no_index:
  directory:
    - t
    - inc
provides:
  Map::Tube::Barcelona:
    file: lib/Map/Tube/Barcelona.pm
    version: '0.12'
  Map::Tube::Barcelona::Line::L11:
    file: lib/Map/Tube/Barcelona/Line/L11.pm
    version: '0.12'
  Map::Tube::Barcelona::Line::L3:
    file: lib/Map/Tube/Barcelona/Line/L3.pm
    version: '0.12'
  Map::Tube::Barcelona::Line::L4:
    file: lib/Map/Tube/Barcelona/Line/L4.pm
    version: '0.12'
requires:
  File::Share: '0'
  File::ShareDir::Install: '0'
  Map::Tube: '2.46'
  Moo: '0'
  namespace::clean: '0'
  perl: '5.006'
resources:
  repository: https://github.com/Manwar/Map-Tube-Barcelona.git
version: '0.12'

